models/Binar.php
<?php
namespace app\models;

use yii\db\ActiveRecord;

/**
 * Class Binar
 * @package app\models
 */
class Binar extends ActiveRecord{}

models/BuildBinar.php
<?php
namespace app\models;

use yii\base\Model;

/**
 * Class BuildBinar
 * @package app\models
 */
class BuildBinar extends Model
{
    public $view;

    /**
     * @param int $max_level
     */
    public function run($max_level = 5){

        $level = 1;
        $arr[] = 1;
        while ($level < $max_level) {
            $arrChild = $this->write($arr);
            unset($arr);
            $arr = $arrChild;
            $level++;
        }
    }

    /**
     * @param $arr
     * @return array
     */
    public function write($arr) {
        foreach ($arr as $parent_id) {
            $arrChild[] = WriteBinar::write($parent_id,1);
            $arrChild[] = WriteBinar::write($parent_id,2);
        }
        return $arrChild;
    }

    /**
     * @param $id
     * @return array
     */
    public function getCell($id) {
        // Get Parent cells
        $cell = Binar::findOne($id);
        $path = $cell->path;
        $before = explode('.', $path);
        array_pop($before);

        // Get Children cells
        $children = new Binar;
        $childrenArray = $children->find()
            ->where(['like', 'path', $path])
            ->asArray(true)
            ->all();
        array_shift($childrenArray);

        /*
        $parents[] = $id;
        do{
            $parents = $this->getChildren($parents);
        }while($parents);
        */
        return array('before' => $before, 'after' => $this->after);
    }

    public function paintBinar () {
        $parents[] = 1;
        $this->view = '<div class="binar-row"><div>1</div></div>';
        do{
            $parents = $this->getChildren($parents);
        }while($parents);

        return $this->view;
    }

    /**
     * @param $parents
     * @return array|bool
     */
    public function getChildren($parents) {
        $nextParents = array();
        $this->view .= '<div class="binar-row">';
        foreach ($parents as $parent) {
            $model = new Binar;
            $children =$model->find()->where(['parent_id' => $parent])->all();
            if (!$children){
                return false;
            }

            foreach ($children as $child) {
                $nextParents[] = $child->id;
                $this->view .= '<div>' . $child->id . '</div>';
            }
        }
        $this->view .= '</div>';

        return $nextParents;
    }
}

models/BuildForm.php
<?php
namespace app\models;


use yii\base\Model;

class BuildForm extends Model
{
    public $level;

    public function rules() {

        return [

            ['level', 'required'],
            ['level', 'number', 'min' => 2, 'max' => 10],
        ];

    }
}

models/CellForm.php
<?php
namespace app\models;


use yii\base\Model;

class CellForm extends Model
{
    public $id;

    public function rules() {

        return [

            ['id', 'required'],
            ['id', 'number', 'min' => 1, 'max' => 1000],
        ];

    }
}

models/MoveCellForm.php
<?php
namespace app\models;


use yii\base\Model;

class MoveCellForm extends Model
{
    public $id;
    public $parentId;

    public function rules() {

        return [

            [['id', 'parentId'], 'required'],
            ['id', 'number', 'min' => 1, 'max' => 1000],
            ['parentId', 'number', 'min' => 1, 'max' => 1000],
        ];

    }
}

models/WriteBinar.php
<?php
namespace app\models;

use yii\base\Model;

/**
 * Class WriteBinar
 * @package app\models
 */
class WriteBinar extends Model
{
    /**
     * @param $parent_id
     * @param $position
     * @return mixed|string
     */
    public static function write($parent_id, $position) {
        // Check if cell is empty
        if (!empty(Binar::find()->where(['parent_id' => $parent_id, 'position' => $position])->all())) {
            return 'Not empty';
        }elseif (Binar::find()->where(['id' => $parent_id])->all()){
            $parent = Binar::findOne($parent_id);

            $binar = new Binar;
            $binar->parent_id = $parent_id;
            $binar->position = $position;
            $binar->level = $parent->level + 1;
            $binar->save();
            $binar->path = $parent->path . '.' . $binar->id;
            $binar->save();
            return $binar->id;
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Binar;
use app\models\BuildBinar;
use app\models\BuildForm;
use app\models\CellForm;
use app\models\MoveCellForm;
use yii\web\Controller;
use Yii;

class SiteController extends Controller
{
    public function actionIndex()
    {
        $request = Yii::$app->getRequest();
        $text = $request->get('result') ?: '';
        $picture = $request->get('picture') ?: '';
        $build = new BuildForm();
        $cell = new CellForm();
        $move_cell = new MoveCellForm();

        return $this->render('index', [
            'result' => $text,
            'picture' => $picture,
            'form_build' => $build,
            'form_cell' => $cell,
            'form_move_cell' => $move_cell]);
    }

    public function actionBuild()
    {
        if (Binar::find()->where(['parent_id' => 1])->all()) {
            return $this->redirect('index?result=Binar not empty!');
        }

        $model = new BuildForm();
        if ($model->load(Yii::$app->request->get()) && $model->validate()) {
            $binar = new BuildBinar();
            $binar->run($model->level);
        }

        return $this->redirect('index?result=Binar is write!');
    }

    public function actionGetcell() {
        $model = new CellForm();
        if ($model->load(Yii::$app->request->get()) && $model->validate()) {
            if (!Binar::find()->where(['id' => $model->id])->all()) {
                return $this->redirect('index?result=Cell not found!');
            }
            $binar = new BuildBinar();
            $result = $binar->getCell($model->id);
        }

        return $this->render('cell', [
            'cell' => $model->id,
            'cells' => $result,
            ]);
    }

    public function actionMovecell()
    {
        $model =new MoveCellForm;
        if ($model->load(Yii::$app->request->get()) && $model->validate()) {
            if (!Binar::find()->where(['id' => $model->id])->all()) {
                return $this->redirect('index?result=Cell not found!');
            } elseif (!Binar::find()->where(['id' => $model->parentId])->all()) {
                return $this->redirect('index?result=Parent Cells not fount');
            } elseif (Binar::find()->where(['parent_id' => $model->parentId])->all()) {
                return $this->redirect('index?result=Cells is not empty');
            }

            return $this->redirect('index?result=Cell is Move!');
        }
    }

    public function actionPaint()
    {
        $binar = new BuildBinar;
        $view = $binar->paintBinar();

        return $this->redirect('index?picture=' . $view);
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">

    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; By Neodimius <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/cell.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">

    <div class="body-content">
        <a href="index.php" class="btn btn-danger">HOME</a>
        <h3>For Cell with id <?= $cell; ?></h3>
        <?php if (isset($cells)) :?>
            <h3>Parent cells:</h3>
            <ul>
                <?php foreach ($cells['before'] as $cell) :?>
                    <li><?= $cell; ?></li>
                <?php endforeach; ?>
            </ul>

            <h3>Children cells:</h3>
            <ul>
                <?php foreach ($cells['after'] as $cell) :?>
                    <li><?= $cell['id']; ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif;?>
    </div>
</div>

views/site/index.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Building Binar';
?>
<div class="site-index">

    <?php if (isset($result)) :?>
        <h3 class="text-danger"><?= $result; ?></h3>
    <?php endif ?>
    <h2>Buid binar with current level:</h2>

        <?php $form = ActiveForm::begin([
            'method' => 'get',
            'action' => Url::to(['site/build']),
        ]) ?>
            <?= $form->field($form_build, 'level') ?>
            <?= Html::submitButton('Buid binar', ['class' => 'btn btn-success']) ?>
        <?php ActiveForm::end() ?>

    <h2>Get cell`s parents and children:</h2>

        <?php $form = ActiveForm::begin([
            'method' => 'get',
            'action' => Url::to(['site/getcell']),
        ]) ?>
        <?= $form->field($form_cell, 'id') ?>
        <?= Html::submitButton('Check Cell by id', ['class' => 'btn btn-success']) ?>
        <?php ActiveForm::end() ?>

    <h2>Move cell by id to position:</h2>

        <?php $form = ActiveForm::begin([
            'method' => 'get',
            'action' => Url::to(['site/movecell']),
        ]) ?>
        <?= $form->field($form_move_cell, 'id') ?>
        <?= $form->field($form_move_cell, 'parentId') ?>
        <?= Html::submitButton('Move', ['class' => 'btn btn-success']) ?>
        <?php ActiveForm::end() ?>

    <a href="index.php?r=site%2Fpaint" class="btn btn-danger">Paint Binar</a>

    <?php if (isset($picture)) :?>
        <?= $picture; ?>
    <?php endif ?>

    </div>